service: serverless-ssr

plugins:
  - serverless-offline
  - serverless-apigw-binary

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs8.10
  stage: development
  region: eu-west-1
  deploymentBucket: 'bucket'
  endpointType: regional

package:
  exclude:
    - ./**
  include:
    - build/**

functions:
  ssr:
    timeout: 30
    handler: build/lambda.handler
    events:
      - http:
          method: any
          cors: true
          path: /{proxy+}